### ISSUE TITLE
install packages instance failed

### ISSUE THREAD

**Issue by AngryMills** [wonderfulsuccess/weixin_crawler#1]
Looking in indexes: http://pypi.douban.com/simple/
Collecting instance

  The repository located at pypi.douban.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host pypi.douban.com'.
  Could not find a version that satisfies the requirement instance (from versions: )
No matching distribution found for instance

去pip官网也找不到这个 instance 库的下载，怎么破?

**Comment by wonderfulsuccess** [comment]
instance 是项目自带的一个模块 详见weixin_crawler/project/instance

**Comment by AngryMills** [comment]
感谢回复

**Comment by AngryMills** [comment]
![image](https://user-images.githubusercontent.com/19707438/49628712-cec95a80-fa20-11e8-8867-b56e95a107cd.png)
是我下载的代码不全么？

**Comment by AngryMills** [comment]
嗯，设置错跟目录了。谢谢
 python无法import Aipocr的问题：
pip install baidu-aip

**Comment by AngryMills** [comment]
anyproxy根本没法用啊，看到issue说闪崩也没人解决，自己安了也是一样。有没有考虑换别的稳定一点的代理。

**Comment by AngryMills** [comment]
node8版本可以，10和11都不行。

**Comment by AngryMills** [comment]
已经安装了node和anyproxy
还是不太理解这句。
cd to weixin_crawler/proxy and run node proxy.js
怎么运行proxy.js，什么意思

**Comment by wonderfulsuccess** [comment]
anyprpxy官方github最后一次提交代码是4个月以前，应该是在持续维护，不必担心无法使用的问题。

1. cd wexin_crawler/proxy
2. npm install anyproxy
3. npm install redis
4. node proxy.js

after each of command above finished without any error
open localost:8002 in browser

**Comment by wonderfulsuccess** [comment]
command node *.js is how nodejs run a js script

**Comment by AngryMills** [comment]
thanks for replaying.
Can redis and mongo use online , not local?

**Comment by wonderfulsuccess** [comment]
Sure， tell weixin crawler the right ip and port

**Comment by AngryMills** [comment]
anyproxy's redis has anything to do with the crawler's redis?
Now I have a problem about redis' dataType.
![image](https://user-images.githubusercontent.com/19707438/49641823-3e087400-fa4c-11e8-99c5-ed9a6201aaf9.png)

**Comment by wonderfulsuccess** [comment]
anyproxy 工具本身不会使用到redis，在anrpoxy的自定义脚本proxy.js中将符合条件url的请求参数存入的redies 均为键值对的形式存入 key以.req结尾，值均为字符串。
python中也仅仅用到redis存储需要爬取的公众号任务队列，存储在一个全局唯一的key中value为一个list，两方对redis的操作并不会相互干扰。
针对你出现的错误我建议使用tools/data_queue.py中的提供的类进行单元测试，good luck
