### ISSUE TITLE
Redis中已经有存入了数据，但是Spider却没有抓到任何信息

### ISSUE THREAD

**Issue by qingwuh** [wonderfulsuccess/weixin_crawler#10]
![image](https://user-images.githubusercontent.com/45593400/50054943-0489e400-0183-11e9-9985-43a153a73ab3.png)
Redis中已经有存入了数据，但是Spider却没有抓到任何信息
![image](https://user-images.githubusercontent.com/45593400/50054951-2aaf8400-0183-11e9-80ac-80525ae8f51c.png)

**Comment by qingwuh** [comment]
> Hi，
> 可能是部分Python包没安装，确保requirements.txt中的每一个包均安装
> 但尚需更多信息才能做出判断，比如执行的完整操作步骤

你好，我重新安装了一遍Python包，可以抓到标题了，但是正文和阅读数据没有，
![image](https://user-images.githubusercontent.com/45593400/50069421-f11f5d00-0204-11e9-839b-841bf69d9f44.png)
添加公众号时这几个选项都试过了，请问该怎么操作呢？

**Comment by wonderfulsuccess** [comment]
能提供更多的错误信息？信息太少 不好诊断

**Comment by qingwuh** [comment]
> 能提供更多的错误信息？信息太少 不好诊断

就是没有任何报错信息，只能抓到标题，没有正文和阅读评论等

**Comment by qingwuh** [comment]
> 能提供更多的错误信息？信息太少 不好诊断

raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', 'analyzer [ik_max_word] not found for field [title]')
只报了这个错误

**Comment by wonderfulsuccess** [comment]
我想原因应该是这样的，需要为es安装一个分词器。

**Comment by qingwuh** [comment]
> 我想原因应该是这样的，需要为es安装一个分词器。

你好，安装分词器后不再报上边的错误了，但是提示“索引完成 (0, [])”，这是什么原因了？同样的只能抓到标题，没有评论

**Comment by wonderfulsuccess** [comment]
安装的是什么分词器，参考最新readme

**Comment by qingwuh** [comment]
> 安装的是什么分词器，参考最新readme

你好，问题已解决，是我加了一个log引起的bug。谢谢！
