### ISSUE TITLE
运行 python main.py报错

### ISSUE THREAD

**Issue by exl2** [wonderfulsuccess/weixin_crawler#15]
1.启动了mongodb、anyproxy，http://localhost:27017/、http://localhost:8002/正常，
2.adb devices正常，返回5037端口
3.http://localhost:5000/正常显示，添加了ip:5037爬虫，以手动模式添加了公众号
4.进入C:\weixin_crawler-master\project，python main.py后，直接报错
![_20190102202722](https://user-images.githubusercontent.com/25222104/50591923-f3eca400-0ecc-11e9-88a7-049826373569.png)

**Comment by wonderfulsuccess** [comment]
爬取文章之前，需要先正确操作手机。建议看看相关的issue

**Comment by DesertsX** [comment]
> 爬取文章之前，需要先正确操作手机。建议看看相关的issue

这的项目没有其他的issue吧？只有这一条哈

**Comment by wonderfulsuccess** [comment]
其余issue已经关闭 仍旧可以查看
@DesertsX
