### ISSUE TITLE
手动模式 无法获取文章内容 可以获取文章列表

### ISSUE THREAD

**Issue by Etran-H** [wonderfulsuccess/weixin_crawler#20]
【手动模式】+【仅标题】下后台显示可以获取文章列表，MongoDB 也有数据，但是UI 界面不显示在已经完成内。
![image](https://user-images.githubusercontent.com/34226782/53864554-bd93e800-4027-11e9-8373-9b8487cf1117.png)
![image](https://user-images.githubusercontent.com/34226782/53864576-c84e7d00-4027-11e9-9456-0e1b54d2deb1.png)
【手动模式】+【含文章】下获取文章列表后，无法获取文章内容。
![image](https://user-images.githubusercontent.com/34226782/53864731-3004c800-4028-11e9-97a8-e6f002e77acc.png)
![image](https://user-images.githubusercontent.com/34226782/53864774-5460a480-4028-11e9-9bb3-6c287577d16d.png)

node
![image](https://user-images.githubusercontent.com/34226782/53864875-94278c00-4028-11e9-8a4c-e6f3215e966e.png)
elasticsearch
![image](https://user-images.githubusercontent.com/34226782/53864909-a6a1c580-4028-11e9-9c38-25fde0835c38.png)
除gevent 为1.4.0 外(找不到1.3.7、win32的版本)，都安装了推荐的版本号。

**Comment by wonderfulsuccess** [comment]
应该是手机操作不全，没有点开一篇文章，已经关闭的issue中有详细操作步骤或者上知识星球寻求详细文档

**Comment by Etran-H** [comment]
还有一个问题是elasticsearch 的ik 插件路径问题。ik 插件路径不能有空格和中文。
