### ISSUE TITLE
node proxy.js error

### ISSUE THREAD

**Issue by JieZhaoAllen** [wonderfulsuccess/weixin_crawler#4]
![image](https://user-images.githubusercontent.com/25027918/49723703-74d7c780-fca2-11e8-8636-3a1483b08225.png)

**Comment by wonderfulsuccess** [comment]
try the following commands pls
$ cd weixin_crawler/proxy
$ npm install anyproxy
$ npm install redis
$ node proxy.js

**Comment by leelijin** [comment]
I  meet this error too ,
and solve it by 
```npm install -g anyproxy```
