### ISSUE TITLE
添加公众号爬取任务成功但是程序似乎没有运行

### ISSUE THREAD

**Issue by liubaicai** [wonderfulsuccess/weixin_crawler#6]
感谢辛苦工作，将您的项目下载下来后遇到一些问题，似乎不能工作
clone后，启动了后台数据库和代理，启动了main.py，连接了手机，在local5000页面添加了爬虫。添加公众号后，main.py 显示连接手机，然后微信自动点击公众号搜索输入公众号名字，点进去，点右上角，下拉，**点了全部消息上面的那一行消息**，下拉到评论，然后退出退出直到桌面。mongo内有三条数据phone_adb_ports，公众号，类别。redis内有数条xxx.xxx.req，current_nickname，tidy_req_data, xx.nick_name。proxy的8002界面也能看到大量wx的url请求。
然后，然后**localhost:5000的公众号界面一直停在人民日报正在进行，UNK/UNK，UNK，UNK
刷新会消失，没有任何数据，似乎也没有进行下一步的什么动作。**
请问是哪个步骤不太对呢？

**Comment by wonderfulsuccess** [comment]
也许weixin_crawler正在工作...
两个地方可以查看爬取状态:

1. UI界面的Crawler/采集 菜单
2. 启动main.py脚本的终端

如果没有任何输出消息，根据源码调试试试

**Comment by liubaicai** [comment]
解决了，与
