### ISSUE TITLE
手动模式下，启了python+node+其它数据库服务，但还是未开始采集，也没有报错

### ISSUE THREAD

**Issue by leelijin** [wonderfulsuccess/weixin_crawler#7]
1. 运行了 python：
![image](https://user-images.githubusercontent.com/8479448/49843445-41a84c00-fdfa-11e8-8ca3-0311439c49ec.png)
2. 运行了node：
![image](https://user-images.githubusercontent.com/8479448/49843482-5be22a00-fdfa-11e8-8390-62b77a9cf338.png)
3. 在8002页面也有大量手机操作的请求：
![image](https://user-images.githubusercontent.com/8479448/49843540-8fbd4f80-fdfa-11e8-8606-7f895c9e1d3e.png)
4. mongo 数据如下：
![image](https://user-images.githubusercontent.com/8479448/49843591-b4192c00-fdfa-11e8-9017-65efd45192d7.png)
5. redis 数据如下：
![image](https://user-images.githubusercontent.com/8479448/49843611-c3987500-fdfa-11e8-9c4f-beff4ccac4b8.png)
![image](https://user-images.githubusercontent.com/8479448/49843778-46b9cb00-fdfb-11e8-9fc5-a89dd84e8857.png)

6. 5000端口页面也添加了爬虫和公众号：（adb是非手动模式使用，所以我是用手机手动点的微信消息列表）
![image](https://user-images.githubusercontent.com/8479448/49843655-e591f780-fdfa-11e8-8ddd-b43e55f1c58b.png)
![image](https://user-images.githubusercontent.com/8479448/49843667-ee82c900-fdfa-11e8-85c3-d75d1143b2c3.png)

接下来使用手机操作浏览相关公众号的”全部消息“页面，但在手动模式下，5000端口页面也并未显示采集中。

是否会是以下原因：
node没有监听到代理请求？
还是python脚本没有成功入库？

感谢大佬。

**Comment by wonderfulsuccess** [comment]
这是一个非常好的问题！谢谢

从redis中的请求参数来看，手机操作部分没有问题。
排除 node没有监听到代理请求的可能性
如果存在Python库没导入成功终端会直接报错

我在win10环境下尝试按照你的做法，使用了空白的数据库依然无法复现你的问题
怀疑：
1. 你可能修改了部分源码
2. 可能是mac环境下部分代码不支持（具体有哪些，需要排坑....）

尝试建议：在同一局域网内使用win系统PC，运行Python脚本。至于anyproxy、redis、mongodb可依旧运行在mac环境中

**Comment by wonderfulsuccess** [comment]
你是否遇到了issue#5所描述的问题，经过大家的讨论可能是redis的版本问题，在程序运行起来之前不建议随意修改源码。

**Comment by liubaicai** [comment]
我与一楼问题一样，也是mac系统，并未修改源码。目前已经在windows下搭建环境准备测试。另外，pip的redis版本确实有问题，高于3.0添加公众号会报错，某些数据类型新版似乎不支持，降级为2.10.6后解决，但是依然有不工作的问题，所以原因应该不是因为这个。

**Comment by leelijin** [comment]
最后通过检查源码，打断点的方式
发现在执行到
/project/crawler/crawler/spiders/article_list.py 时 出现以下包缺失的错误
![image](https://user-images.githubusercontent.com/8479448/49852891-58619980-fe20-11e8-96fc-3eac2099bc59.png)

所以解决方法是：
pip install html2text 
再次执行添加公众号时，已经成功添加上，pyhon终端也有反应正在执行scrapy：
![image](https://user-images.githubusercontent.com/8479448/49852900-66afb580-fe20-11e8-8c05-1c75ae402de7.png)

但又发现另外的错误
![image](https://user-images.githubusercontent.com/8479448/49852911-74fdd180-fe20-11e8-9ef3-4c71536c2d6a.png)

似乎又是一个新问题。:)

**Comment by wonderfulsuccess** [comment]
尴尬了  这是我的失误 忘记一个包html2text
新出现的错误，可能是因为你没有修改Scrapy详见read me文档。

**Comment by leelijin** [comment]
新问题，
通过覆盖以下三个文件解决了此问题

`scrapy Python36\Lib\site-packages\scrapy\http\request\ _init_.py --> weixin_crawler\source_code\request\__init__.py`
`scrapy Python36\Lib\site-packages\scrapy\http\response\ _init_.py --> weixin_crawler\source_code\response\_init_.py`
`pyecharts Python36\Lib\site-packages\pyecharts\base.py --> weixin_crawler\source_code\base.py. In this case function get_echarts_options is added in line 106`

再重新启动python, 手机手动浏览一些文章，再次添加公众号，发现已经开始采集。

![image](https://user-images.githubusercontent.com/8479448/49855740-0f621300-fe29-11e8-910a-b47d02d5955f.png)
![image](https://user-images.githubusercontent.com/8479448/49855746-12f59a00-fe29-11e8-9b5b-b6b641849ac7.png)

**Comment by 545818924** [comment]
> 新问题，
> 通过覆盖以下三个文件解决了此问题
> 
> `scrapy Python36\Lib\site-packages\scrapy\http\request\ _init_.py --> weixin_crawler\source_code\request\__init__.py`
> `scrapy Python36\Lib\site-packages\scrapy\http\response\ _init_.py --> weixin_crawler\source_code\response\_init_.py`
> `pyecharts Python36\Lib\site-packages\pyecharts\base.py --> weixin_crawler\source_code\base.py. In this case function get_echarts_options is added in line 106`
> 
> 再重新启动python, 手机手动浏览一些文章，再次添加公众号，发现已经开始采集。
> 
> ![image](https://user-images.githubusercontent.com/8479448/49855740-0f621300-fe29-11e8-910a-b47d02d5955f.png)
> ![image](https://user-images.githubusercontent.com/8479448/49855746-12f59a00-fe29-11e8-9b5b-b6b641849ac7.png)

我手动模式也到了这情况，win10，覆盖文件和手动查看了weixin_crawler\source_code\base.py中 106行，get_echarts_options 函数存在，现在卡在这里了，是否需要再修改其他文件呢？

**Comment by 545818924** [comment]
![default](https://user-images.githubusercontent.com/12145494/50783148-f7c16180-12e4-11e9-94e4-95806bf285bc.PNG)
现在问题成这样，没有获得昵称
